inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - bin/**
    - vendor/**/*
    - db/migrate/*
    - db/schema.rb
    - config.ru
    - tmp/**/*
    - public/**/*

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Rubycw:
  Enabled: true

Security:
  Enabled: true

Style/Documentation:
  Enabled: false
